name: Deploy MAAP Email Forwarder

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FROM_EMAIL: ${{ vars.FROM_EMAIL }}
      SUBJECT_PREFIX: ${{ vars.SUBJECT_PREFIX }}
      EMAIL_BUCKET: ${{ vars.EMAIL_BUCKET }}
      EMAIL_KEY_PREFIX: ${{ vars.EMAIL_KEY_PREFIX }}
      FORWARD_MAPPING: ${{ vars.FORWARD_MAPPING }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run unit tests
        run: uv run pytest -q

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          role-to-assume: ${{ vars.DEPLOY_ROLE }}
          aws-region: 'us-west-2' # This should not be changed

      - name: CDK Deploy
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: uv run npx cdk deploy --require-approval never --all
